"""Hermetic tests for the image-generation pipeline.

Two tests:

* The image-model picker honours both the ``image_gen``-capable
  filter and the independence-mode filter, and raises
  ``NoImageProviderError`` when no eligible model exists.
* End-to-end ``run_roitelet_image_chat`` writes the generated bytes
  to disk and records the path on the assistant message metadata.

K=1 by design — no fusion — so this is the whole testable surface.
"""

from __future__ import annotations

import json
import shutil
import time
from pathlib import Path

import pytest

from core.schemas import (
    AppSettingsPayload,
    GeneratedImage,
    ImageGenRequest,
    ImageGenResponse,
    RouterPreferences,
)


def _seed_tmp(tmp_path: Path, with_image_model: bool = True) -> None:
    """Seed a temp data dir with priors, optionally including a fake image-gen model."""
    src = Path(__file__).resolve().parent.parent / 'data' / 'bootstrap'
    target = tmp_path / 'bootstrap'
    target.mkdir(parents=True, exist_ok=True)
    shutil.copy(src / 'model_priors.json', target / 'model_priors.json')

    if with_image_model:
        priors = json.loads((target / 'model_priors.json').read_text())
        priors['openai-compatible/test-image'] = {
            'provider': 'openai-compatible', 'local': False, 'vlm': False,
            'pricing': {'input_per_1k': 0.04, 'output_per_1k': 0.0},
            'latency_s': 6.0, 'energy_kwh': 0.0008,
            'capabilities': {
                'coding': 0.0, 'math': 0.0, 'reasoning': 0.0, 'writing': 0.0,
                'analysis': 0.0, 'vision': 0.0, 'multilingual': 0.0,
                'long_context': 0.0, 'image_gen': 0.95,
            },
        }
        (target / 'model_priors.json').write_text(json.dumps(priors))

    for d in ('images', 'conversations', 'telemetry', 'runtime'):
        (tmp_path / d).mkdir(parents=True, exist_ok=True)


def _reset_singletons() -> None:
    from core.config import get_settings
    from core.registry import get_registry, ollama_cache
    from core.storage import get_storage

    get_settings.cache_clear()
    get_storage.cache_clear()
    get_registry.cache_clear()
    ollama_cache._models = []
    ollama_cache._fetched_at = time.monotonic()


def test_picker_obeys_image_gen_independence_and_raises_when_no_eligible_model(tmp_path):
    """The picker is the gate between routing and provider call. One
    test covers the three branches that actually matter:

    * with an ``image_gen``-capable model present, the picker returns it;
    * with ``independence=True`` and no local image-gen model, the
      picker raises (the picker doesn't fall back to remote);
    * with no image-gen model registered at all, the picker raises.
    """
    from core.image_pipeline import NoImageProviderError, _pick_image_model
    from core.registry import ModelRegistry

    # Branch 1: there *is* an eligible (remote) image-gen model.
    with pytest.MonkeyPatch().context() as m:
        m.setenv('ROITELET_DATA_DIR', str(tmp_path))
        _seed_tmp(tmp_path, with_image_model=True)
        _reset_singletons()
        spec = _pick_image_model(
            ModelRegistry(app_settings=AppSettingsPayload(openai_compatible_api_key='sk-test')),
            RouterPreferences(),
        )
        assert spec.model_id == 'openai-compatible/test-image'
        assert spec.capabilities['image_gen'] > 0

        # Branch 2: independence mode strips the remote image-gen model.
        with pytest.raises(NoImageProviderError):
            _pick_image_model(
                ModelRegistry(app_settings=AppSettingsPayload(openai_compatible_api_key='sk-test')),
                RouterPreferences(independence=True),
            )
    _reset_singletons()

    # Branch 3: nothing image-gen-capable registered at all.
    with pytest.MonkeyPatch().context() as m:
        m.setenv('ROITELET_DATA_DIR', str(tmp_path / 'no_image'))
        _seed_tmp(tmp_path / 'no_image', with_image_model=False)
        _reset_singletons()
        with pytest.raises(NoImageProviderError):
            _pick_image_model(ModelRegistry(), RouterPreferences())
    _reset_singletons()


async def test_image_chat_writes_bytes_and_records_assistant_metadata(tmp_path, monkeypatch):
    """Happy path: ``run_roitelet_image_chat`` stubs out the OpenAI
    Images client, writes a one-byte "PNG" to ``data/images/``, and
    persists a conversation whose assistant message points at the
    generated path. The GUI renders these via the static mount —
    if the path isn't in metadata, the picture doesn't show up."""
    with pytest.MonkeyPatch().context() as m:
        m.setenv('ROITELET_DATA_DIR', str(tmp_path))
        _seed_tmp(tmp_path, with_image_model=True)
        _reset_singletons()

        from core import image_pipeline as ip
        from core.storage import get_storage

        # Sentinel keys so the registry doesn't prune the test entry.
        get_storage().save_app_settings(AppSettingsPayload(
            openai_compatible_api_key='sk-test',
            openai_compatible_base_url='https://example.invalid/v1',
        ))

        # Stub: synthesise a one-byte PNG, return its path.
        stub_path = tmp_path / 'images' / 'stub.png'
        stub_path.write_bytes(b'\x89PNG\r\n\x1a\n')

        class _StubClient:
            provider_name = 'openai-compatible'

            async def generate_image(self, **kw):
                return ImageGenResponse(
                    conversation_id='', model_id=kw['model_id'],
                    provider='openai-compatible',
                    images=[GeneratedImage(
                        path=str(stub_path), model_id=kw['model_id'],
                        provider='openai-compatible',
                    )],
                    latency_s=0.1,
                )

        monkeypatch.setattr(ip, 'get_image_client', lambda provider: _StubClient())

        response = await ip.run_roitelet_image_chat(
            ImageGenRequest(prompt='A small wren in a forest, oil painting.'),
        )
        assert response.images[0].path == str(stub_path)
        assert stub_path.exists()

        # The conversation log records the image on the assistant message.
        convo = get_storage().get_conversation(response.conversation_id)
        assert [m.role for m in convo.messages] == ['user', 'assistant']
        assert convo.messages[1].metadata['image_paths'] == [str(stub_path)]
        assert convo.messages[1].metadata['provider'] == 'openai-compatible'
    _reset_singletons()
