/* Roitelet web client.
 *
 * Vanilla JS, no build step. Talks to the FastAPI backend over its native
 * endpoints (no SSE — the OpenAI-compat streaming chunks an already-complete
 * answer, so honest loading state beats fake typing).
 */

const $ = (id) => document.getElementById(id);
const escapeHtml = (s) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const state = {
  conversationId: null,
  messages: [],          // {role, content, metadata?}
  conversations: [],
  busy: false,
  attachments: [],       // File objects queued for the next send
  allowVlms: false,      // mirrors the persisted preference; gates image attachments
};

const AUDIO_RX = /\.(wav|mp3|m4a|flac|ogg|opus|aac)$/i;
const IMAGE_RX = /\.(jpe?g|png|webp|gif|bmp|heic|heif)$/i;
const PDF_RX   = /\.pdf$/i;

function classifyFile(f) {
  const t = (f.type || '').toLowerCase();
  if (t.startsWith('audio/') || AUDIO_RX.test(f.name)) return 'audio';
  if (t.startsWith('image/') || IMAGE_RX.test(f.name)) return 'image';
  if (t === 'application/pdf' || PDF_RX.test(f.name)) return 'pdf';
  return null;
}

// ─── API helpers ─────────────────────────────────────────────────────────────

async function apiGet(path) {
  const r = await fetch(path);
  if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
  return r.json();
}

async function apiPost(path, body) {
  const r = await fetch(path, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(body),
  });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} — ${await r.text()}`);
  return r.json();
}

async function apiPostMultipart(path, formData) {
  const r = await fetch(path, {method: 'POST', body: formData});
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} — ${await r.text()}`);
  return r.json();
}

// ─── UI rendering ────────────────────────────────────────────────────────────

function renderMessages() {
  const inner = $('messagesInner');
  inner.innerHTML = '';
  if (state.messages.length === 0) {
    inner.innerHTML = `
      <div id="welcome" class="text-center py-24">
        <img src="/assets/roitelet.png" alt="Roitelet" width="72" height="72" class="mx-auto mb-5 rounded-[10px] shadow-lg">
        <h2 class="text-[22px] font-semibold tracking-tight">Ask any question.</h2>
        <p class="text-[14px] text-gray-500 dark:text-gray-400 mt-2 max-w-md mx-auto leading-relaxed">Top-K models answer in parallel. A local model fuses the best.</p>
        <p class="text-[12px] text-gray-400 dark:text-gray-500 mt-4 max-w-md mx-auto leading-relaxed">
          Tip — start a message with <code>/image</code>, <code>/personal</code>, <code>/local</code>, <code>/cheap 0.001</code>, <code>/k 5</code>, or <code>/help</code>.
        </p>
      </div>`;
    return;
  }
  for (const m of state.messages) inner.appendChild(messageNode(m));
  scrollToBottom();
}

function messageNode(m) {
  const wrap = document.createElement('div');
  wrap.className = m.role === 'user' ? 'flex justify-end' : 'flex justify-start';

  const bubble = document.createElement('div');
  if (m.role === 'user') {
    bubble.className = 'bg-sysblue text-white px-4 py-2.5 max-w-[78%] text-[15px] leading-relaxed shadow-sm whitespace-pre-wrap';
    bubble.textContent = m.content;
  } else {
    bubble.className = 'bg-gray-100 dark:bg-[#2c2c2e] px-4 py-3 max-w-[85%] text-[15px] leading-relaxed shadow-sm prose-msg';
    bubble.innerHTML = marked.parse(m.content || '', {breaks: true, gfm: true});
    // Image-gen assistant turns: render the generated bytes inline. The
    // static mount at /data/images/<uuid>.png serves them straight from
    // disk, so the <img> src is the on-disk path the API returned with
    // /data prepended (the API returns absolute paths; we use basename).
    if (m.metadata?.imagegen?.images?.length) {
      bubble.appendChild(imageGenNode(m.metadata.imagegen));
    } else if (m.metadata) {
      bubble.appendChild(metadataNode(m.metadata));
    }
  }
  wrap.appendChild(bubble);
  return wrap;
}

function imageGenNode(imgGen) {
  const div = document.createElement('div');
  div.className = 'mt-3 grid grid-cols-1 sm:grid-cols-2 gap-2';
  for (const img of imgGen.images || []) {
    if (img.error) {
      const err = document.createElement('div');
      err.className = 'text-[12px] text-red-500';
      err.textContent = `Image error: ${img.error}`;
      div.appendChild(err);
      continue;
    }
    if (!img.path) continue;
    const basename = img.path.split('/').pop();
    const node = document.createElement('img');
    node.src = `/data/images/${basename}`;
    node.alt = `Generated by ${imgGen.model_id}`;
    node.loading = 'lazy';
    node.className = 'rounded-[10px] shadow-sm';
    div.appendChild(node);
  }
  return div;
}

function metadataNode(meta) {
  const det = document.createElement('details');
  det.className = 'mt-3 pt-3 border-t border-black/5 dark:border-white/10 text-[12px] text-gray-500 dark:text-gray-400';
  const summary = document.createElement('summary');
  summary.className = 'cursor-pointer select-none hover:text-gray-700 dark:hover:text-gray-200 transition-colors';
  const winners = (meta.synthesis?.winning_model_ids || []).map(shortModel).join(', ');
  const selected = (meta.router?.selected_model_ids || []).map(shortModel).join(' · ');
  const caps = Object.entries(meta.router?.categories || {})
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([k, v]) => `${k} ${(v * 100).toFixed(0)}%`)
    .join(' · ');
  summary.textContent = `Roitelet · ${selected || '—'}${winners ? '  ·  won: ' + winners : ''}`;
  det.appendChild(summary);

  const body = document.createElement('div');
  body.className = 'mt-2 space-y-2';
  body.innerHTML = `
    <div><span class="text-gray-400">Capabilities</span> &nbsp;${escapeHtml(caps)}</div>
    <div class="space-y-1.5">
      ${(meta.responses || []).map(r => `
        <div class="flex items-baseline justify-between gap-3">
          <span class="truncate">${escapeHtml(shortModel(r.model_id))}</span>
          <span class="text-gray-400 text-[11px] tabular-nums">${r.latency_s?.toFixed(2) || '—'}s · $${(r.cost_usd || 0).toFixed(4)}</span>
        </div>`).join('')}
    </div>`;
  det.appendChild(body);
  return det;
}

function shortModel(id) {
  if (!id) return '';
  const parts = id.split('/');
  return parts.slice(-2).join('/');
}

function renderConversationList() {
  const list = $('conversationList');
  list.innerHTML = '';
  for (const c of state.conversations) {
    const a = document.createElement('button');
    const active = c.conversation_id === state.conversationId;
    a.className = `w-full text-left px-2.5 py-2 text-[13px] truncate transition-colors ${
      active
        ? 'bg-black/[0.06] dark:bg-white/[0.1] text-gray-900 dark:text-white'
        : 'text-gray-700 dark:text-gray-300 hover:bg-black/[0.03] dark:hover:bg-white/[0.05]'
    }`;
    a.textContent = c.title || 'Untitled';
    a.onclick = () => loadConversation(c.conversation_id);
    list.appendChild(a);
  }
}

function setBusy(busy, label) {
  state.busy = busy;
  $('sendBtn').disabled = busy;
  $('prompt').disabled = busy;
  $('sendIcon').classList.toggle('hidden', busy);
  $('sendSpinner').classList.toggle('hidden', !busy);
  $('statusDot').className = `w-1.5 h-1.5 rounded-full ${busy ? 'bg-sysblue animate-pulse' : 'bg-emerald-500'}`;
  $('statusText').textContent = busy ? (label || 'Thinking…') : 'Ready';
}

function showThinking() {
  const node = document.createElement('div');
  node.id = 'thinkingNode';
  node.className = 'flex justify-start';
  node.innerHTML = `
    <div class="bg-gray-100 dark:bg-[#2c2c2e] px-4 py-3.5 shadow-sm flex items-center gap-1.5">
      <span class="thinking-dot w-1.5 h-1.5 rounded-full bg-gray-400 dark:bg-gray-500"></span>
      <span class="thinking-dot w-1.5 h-1.5 rounded-full bg-gray-400 dark:bg-gray-500"></span>
      <span class="thinking-dot w-1.5 h-1.5 rounded-full bg-gray-400 dark:bg-gray-500"></span>
    </div>`;
  $('messagesInner').appendChild(node);
  scrollToBottom();
}

function hideThinking() {
  $('thinkingNode')?.remove();
}

function scrollToBottom() {
  const m = $('messages');
  m.scrollTop = m.scrollHeight;
}

function showToast(text, kind = 'info') {
  const t = $('toast');
  $('toastText').textContent = text;
  t.classList.remove('hidden');
  clearTimeout(showToast._t);
  showToast._t = setTimeout(() => t.classList.add('hidden'), 3500);
}

// ─── Actions ─────────────────────────────────────────────────────────────────

async function refreshConversations() {
  try {
    state.conversations = await apiGet('/api/conversations');
    renderConversationList();
  } catch (err) {
    showToast('Could not load conversations: ' + err.message);
  }
}

async function refreshPreferences() {
  // Mirror the server's persisted `enable_vlms` so the local gate matches.
  try {
    const cur = await apiGet('/api/settings');
    state.allowVlms = !!cur.enable_vlms;
  } catch { /* harmless: defaults stay */ }
}

async function loadConversation(id) {
  try {
    setBusy(true, 'Loading…');
    const convo = await apiGet(`/api/conversations/${id}`);
    state.conversationId = convo.conversation_id;
    state.messages = convo.messages.map(m => ({
      role: m.role,
      content: m.content,
      metadata: m.metadata && Object.keys(m.metadata).length ? m.metadata : null,
    }));
    $('conversationTitle').textContent = convo.title || 'Chat';
    renderMessages();
    renderConversationList();
  } catch (err) {
    showToast('Could not load conversation: ' + err.message);
  } finally {
    setBusy(false);
  }
}

function newChat() {
  state.conversationId = null;
  state.messages = [];
  state.attachments = [];
  renderAttachments();
  $('conversationTitle').textContent = 'New chat';
  renderMessages();
  renderConversationList();
  $('prompt').focus();
}

// ─── Slash-command pre-dispatch ──────────────────────────────────────────────
//
// Mirrors `core/commands.py`: only the leading token matters and unknown
// commands pass through as plain text. Done client-side so an `/image`
// prompt goes straight to `/api/images` instead of bouncing off the
// chat endpoint's 400. Keep this list in sync with `core/commands.py`.
const IMAGE_CMD_RX  = /^\/(image|image-gen|img)\b\s*/i;
const SPEECH_CMD_RX = /^\/(speech|stt|transcribe)\b\s*/i;

// Helpers for the Personal panel — opening the modal calls the API
// once, the ingest button calls it again, the status is rendered
// inline. Defined at module scope so they're hoisted alongside the
// other API helpers.
async function fetchPersonalStatus() {
  try { return await apiGet('/api/personal'); }
  catch { return null; }
}
async function triggerPersonalIngest(force) {
  return apiPost(`/api/personal/ingest?force=${force ? 'true' : 'false'}`, {});
}
async function refreshPersonalSummary() {
  const s = await fetchPersonalStatus();
  const el = document.getElementById('personalSummary');
  if (!el) return;
  if (!s) { el.textContent = 'Could not reach /api/personal.'; return; }
  el.textContent = `${s.wiki} wiki file(s) · ${s.inbox} inbox file(s) · mode=${s.mode}`;
}

// ─── Personal embedding viz (Karpathy-style) ─────────────────────────────────
//
// 2-D PCA scatter where each dot is one wiki chunk and color is the
// source file. The whole thing renders inline SVG; no extra deps. The
// server projects via numpy SVD and returns the coordinates.

const VIZ_PALETTE = ['#0a84ff','#ff9500','#34c759','#ff3b30','#af52de',
                     '#5856d6','#ff2d55','#5ac8fa','#ffcc00','#a2845e'];

async function openPersonalViz() {
  let payload;
  try { payload = await apiGet('/api/personal/embeddings'); }
  catch (err) { showToast('Could not fetch embeddings: ' + err.message); return; }
  const points = payload?.points || [];
  if (!points.length) {
    showToast('No wiki chunks to visualise, or embedding model unreachable.');
    return;
  }
  renderVizModal(points);
}

function renderVizModal(points) {
  // Lazy: build the modal nodes on first open so the empty case
  // doesn't bloat the DOM.
  let modal = document.getElementById('vizModal');
  if (!modal) {
    modal = document.createElement('div');
    modal.id = 'vizModal';
    modal.className = 'fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm';
    modal.innerHTML = `
      <div class="bg-white dark:bg-[#1c1c1e] w-[95vw] h-[90vh] flex flex-col overflow-hidden rounded-[10px] shadow-2xl">
        <div class="px-5 py-3 border-b border-gray-200 dark:border-white/[0.08] flex items-center justify-between">
          <div>
            <div class="text-[14px] font-semibold">Personal wiki — embedding projection</div>
            <div class="text-[11px] text-gray-500 dark:text-gray-400" id="vizMeta"></div>
          </div>
          <button id="vizClose" class="w-9 h-9 rounded-full flex items-center justify-center hover:bg-black/5 dark:hover:bg-white/10" aria-label="Close">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><path d="M18 6L6 18M6 6l12 12"/></svg>
          </button>
        </div>
        <div class="flex-1 relative">
          <svg id="vizSvg" class="w-full h-full"></svg>
          <div id="vizTooltip"
            class="absolute pointer-events-none max-w-[360px] hidden z-10 px-3 py-2 rounded-[10px] bg-black/85 text-white text-[12px] leading-relaxed shadow-lg"></div>
        </div>
      </div>`;
    document.body.appendChild(modal);
    modal.querySelector('#vizClose').addEventListener('click', () => modal.remove());
    modal.addEventListener('click', e => { if (e.target === modal) modal.remove(); });
  }

  const svg = modal.querySelector('#vizSvg');
  const tooltip = modal.querySelector('#vizTooltip');
  const meta = modal.querySelector('#vizMeta');
  const fileToColor = new Map();
  const colorFor = p => {
    if (!fileToColor.has(p)) fileToColor.set(p, VIZ_PALETTE[fileToColor.size % VIZ_PALETTE.length]);
    return fileToColor.get(p);
  };
  const sources = Array.from(new Set(points.map(p => p.path)));
  meta.textContent = `${points.length} chunks across ${sources.length} file(s) — hover a dot for the excerpt.`;

  const draw = () => {
    const rect = svg.getBoundingClientRect();
    const W = rect.width, H = rect.height;
    svg.setAttribute('viewBox', `0 0 ${W} ${H}`);
    svg.innerHTML = '';
    const xs = points.map(p => p.x), ys = points.map(p => p.y);
    const xmin = Math.min(...xs), xmax = Math.max(...xs);
    const ymin = Math.min(...ys), ymax = Math.max(...ys);
    const margin = 32;
    const sx = x => margin + (W - 2*margin) * (xmax === xmin ? 0.5 : (x - xmin) / (xmax - xmin));
    const sy = y => H - margin - (H - 2*margin) * (ymax === ymin ? 0.5 : (y - ymin) / (ymax - ymin));
    for (const p of points) {
      const c = document.createElementNS('http://www.w3.org/2000/svg','circle');
      c.setAttribute('cx', sx(p.x)); c.setAttribute('cy', sy(p.y));
      c.setAttribute('r', 6); c.setAttribute('fill', colorFor(p.path));
      c.setAttribute('opacity', 0.75);
      c.style.cursor = 'pointer';
      c.addEventListener('mousemove', e => {
        tooltip.classList.remove('hidden');
        tooltip.style.left = (e.clientX - rect.left + 12) + 'px';
        tooltip.style.top  = (e.clientY - rect.top + 12) + 'px';
        tooltip.innerHTML = `<b>${escapeHtml(p.path)}</b> #${p.chunk_index}<br>${escapeHtml(p.text.slice(0, 280))}${p.text.length > 280 ? '…' : ''}`;
      });
      c.addEventListener('mouseleave', () => tooltip.classList.add('hidden'));
      svg.appendChild(c);
    }
  };
  draw();
  // Redraw on window resize so the scatter scales with the modal.
  const onResize = () => { if (document.body.contains(modal)) draw(); else window.removeEventListener('resize', onResize); };
  window.addEventListener('resize', onResize);
}

async function send() {
  const prompt = $('prompt').value.trim();
  const files = state.attachments;
  if ((!prompt && files.length === 0) || state.busy) return;

  const imageMatch  = prompt.match(IMAGE_CMD_RX);
  const speechMatch = prompt.match(SPEECH_CMD_RX);

  const fileLabel = files.length ? files.map(f => `📎 ${f.name}`).join('\n') : '';
  const userBubble = [fileLabel, prompt].filter(Boolean).join('\n\n') || '(attachment only)';
  state.messages.push({role: 'user', content: userBubble});
  $('prompt').value = '';
  renderMessages();
  showThinking();
  setBusy(true);

  try {
    let res;

    if (imageMatch && !files.length) {
      // `/image <prompt>` → image-gen pipeline. K=1, no fusion.
      const cleanPrompt = prompt.slice(imageMatch[0].length).trim();
      if (!cleanPrompt) throw new Error('`/image` needs a prompt after the command');
      const payload = {
        prompt: cleanPrompt,
        conversation_id: state.conversationId,
        size: '1024x1024',
        n: 1,
      };
      const imgRes = await apiPost('/api/images', payload);
      state.conversationId = imgRes.conversation_id;
      state.messages.push({
        role: 'assistant',
        content: `Generated **${imgRes.images?.length || 0}** image(s) with \`${imgRes.model_id}\`.`,
        metadata: {imagegen: imgRes},
      });
    } else if (speechMatch && !files.length) {
      // `/speech` without an attachment is meaningless — explain.
      throw new Error('`/speech` requires an audio attachment. Click the paperclip first.');
    } else if (files.length) {
      const fd = new FormData();
      // Strip the leading slash command before forwarding to the
      // multimodal endpoint so the inner pipeline sees a clean prompt.
      const stripped = speechMatch ? prompt.slice(speechMatch[0].length).trim() : prompt;
      fd.append('prompt', stripped);
      if (state.conversationId) fd.append('conversation_id', state.conversationId);
      fd.append('top_k', '3');
      fd.append('allow_vlms', state.allowVlms ? 'true' : 'false');
      for (const f of files) fd.append('files', f);
      res = await apiPostMultipart('/api/chat/multimodal', fd);
      finalizeChatResponse(res);
    } else {
      const payload = {
        prompt,
        conversation_id: state.conversationId,
        preferences: {raw_power: 0.7, frugality: 0.3, independence: false, allow_vlms: state.allowVlms},
        top_k: 3,
      };
      res = await apiPost('/api/chat', payload);
      finalizeChatResponse(res);
    }
    state.attachments = [];
    renderAttachments();
    hideThinking();
    renderMessages();
    await refreshConversations();
  } catch (err) {
    hideThinking();
    showToast('Pipeline error: ' + err.message);
    // Keep the user's message visible; don't auto-rewind.
  } finally {
    setBusy(false);
    $('prompt').focus();
  }
}

// Push the standard `/api/chat` response into the message list.
// Extracted so the `/image` and `/speech` branches can take their own
// shape without forking the whole send() body.
function finalizeChatResponse(res) {
  state.conversationId = res.conversation_id;
  state.messages.push({
    role: 'assistant',
    content: res.synthesis?.content || '(no answer)',
    metadata: {
      router: res.router,
      responses: res.responses,
      synthesis: res.synthesis,
    },
  });
}

// ─── Attachments ─────────────────────────────────────────────────────────────

function renderAttachments() {
  const box = $('attachmentChips');
  if (!state.attachments.length) {
    box.classList.add('hidden');
    box.innerHTML = '';
    return;
  }
  box.classList.remove('hidden');
  box.classList.add('flex');
  box.innerHTML = state.attachments.map((f, i) => `
    <span class="inline-flex items-center gap-1.5 px-2.5 py-1 text-[12px] bg-black/5 dark:bg-white/10 text-gray-700 dark:text-gray-200">
      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg>
      <span class="truncate max-w-[180px]">${escapeHtml(f.name)}</span>
      <button data-i="${i}" class="attachRm text-gray-400 hover:text-red-500" title="Remove">×</button>
    </span>`).join('');
  for (const btn of box.querySelectorAll('.attachRm')) {
    btn.addEventListener('click', () => {
      state.attachments.splice(parseInt(btn.dataset.i, 10), 1);
      renderAttachments();
    });
  }
}

function onFilesPicked(fileList) {
  for (const f of fileList) {
    const kind = classifyFile(f);
    if (!kind) {
      showToast(`Skipped ${f.name} — only audio, image, or PDF.`);
      continue;
    }
    if (kind === 'image' && !state.allowVlms) {
      showToast(`Skipped ${f.name} — enable "Allow vision-language" in Settings to attach images.`);
      continue;
    }
    state.attachments.push(f);
  }
  renderAttachments();
}

// ─── Settings sheet ──────────────────────────────────────────────────────────

// `csv-list` fields are persisted as `List[str]` server-side but edited
// as a comma-separated string in the UI for one-line tractability. The
// (de)serialisation happens at the form-submit boundary, not in state.
const SETTINGS_FIELDS = [
  // Local stack
  {key: 'ollama_base_url',                  label: 'Ollama base URL',                  type: 'text',     placeholder: 'http://localhost:11434'},
  {key: 'local_synthesis_model',            label: 'Local synthesis model',            type: 'text',     placeholder: 'qwen3:8b'},
  {key: 'local_vlm_model',                  label: 'Local VLM (image captioning)',     type: 'text',     placeholder: 'qwen2.5vl:7b'},
  {key: 'selected_ollama_models',           label: 'Extra Ollama models (comma-sep)',  type: 'csv-list', placeholder: 'phi4-mini:3.8b, gemma3:4b'},

  // Paid providers
  {key: 'openrouter_api_key',               label: 'OpenRouter API key',               type: 'password'},
  {key: 'paid_openrouter_models',           label: 'OpenRouter models (comma-sep)',    type: 'csv-list', placeholder: 'anthropic/claude-3.7-sonnet'},
  {key: 'openai_api_key',                   label: 'OpenAI API key',                   type: 'password'},
  {key: 'anthropic_api_key',                label: 'Anthropic API key',                type: 'password'},
  {key: 'gemini_api_key',                   label: 'Gemini API key',                   type: 'password'},
  {key: 'perplexity_api_key',               label: 'Perplexity API key',               type: 'password'},

  // Universal OpenAI-compatible (Mistral, Together, Groq, llama-server, …)
  {key: 'openai_compatible_base_url',       label: 'OpenAI-compat base URL',           type: 'text',     placeholder: 'https://api.mistral.ai/v1'},
  {key: 'openai_compatible_api_key',        label: 'OpenAI-compat API key',            type: 'password'},
  {key: 'paid_openai_compatible_models',    label: 'OpenAI-compat models (comma-sep)', type: 'csv-list', placeholder: 'mistral-large-latest'},

  // Routing knobs
  {key: 'raw_power_weight',                 label: 'Raw power weight',                 type: 'number', step: '0.05', min: 0, max: 1},
  {key: 'frugality_weight',                 label: 'Frugality weight',                 type: 'number', step: '0.05', min: 0, max: 1},
  {key: 'independence_local_only',          label: 'Local models only',                type: 'checkbox'},
  {key: 'enable_vlms',                      label: 'Allow vision-language',            type: 'checkbox'},
];

function csvParse(raw) {
  return String(raw || '')
    .split(',')
    .map(s => s.trim())
    .filter(Boolean);
}
function csvFormat(list) {
  return Array.isArray(list) ? list.join(', ') : '';
}

async function openSettings() {
  let current = {};
  try { current = await apiGet('/api/settings'); }
  catch (err) { showToast('Could not load settings: ' + err.message); return; }

  const form = $('settingsForm');
  form.innerHTML = '';

  // Personal-mode panel — shows current corpus state and exposes an
  // "Ingest now" button that walks data/personal/inbox/ via the
  // multimodal extractors. Lives at the top of the sheet so it's
  // discoverable without scrolling past every credential.
  const personalPanel = document.createElement('div');
  personalPanel.className = 'mb-4 p-3 rounded-[10px] bg-black/5 dark:bg-white/[0.05] space-y-2';
  personalPanel.id = 'personalPanel';
  personalPanel.innerHTML = `
    <div class="flex items-center justify-between">
      <div>
        <div class="text-[13px] font-semibold">Personal knowledge base</div>
        <div class="text-[11px] text-gray-500 dark:text-gray-400" id="personalSummary">Loading…</div>
      </div>
      <div class="flex items-center gap-1.5">
        <button type="button" id="personalVizBtn"
          class="min-h-[32px] px-3 py-1 text-[12px] font-medium border border-gray-300 dark:border-white/[0.12] hover:bg-black/5 dark:hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-sysblue/60">
          Visualize
        </button>
        <button type="button" id="personalIngestBtn"
          class="min-h-[32px] px-3 py-1 text-[12px] font-medium bg-sysblue text-white hover:bg-sysblueHover focus:outline-none focus-visible:ring-2 focus-visible:ring-sysblue/60">
          Ingest inbox
        </button>
      </div>
    </div>
    <p class="text-[11px] text-gray-500 dark:text-gray-400 leading-relaxed">
      Drop audio, image, PDF, or Markdown files into <code>data/personal/inbox/</code>. Click <em>Ingest inbox</em>
      to convert them via whisper.cpp / Ollama VLM / kreuzberg. Hand-edited <code>.md</code> files in
      <code>data/personal/wiki/</code> are picked up automatically. Use <code>/personal &lt;question&gt;</code>
      in chat to query the knowledge base.
    </p>
  `;
  form.appendChild(personalPanel);
  refreshPersonalSummary();
  $('personalVizBtn').addEventListener('click', openPersonalViz);
  $('personalIngestBtn').addEventListener('click', async () => {
    const btn = $('personalIngestBtn');
    btn.disabled = true;
    btn.textContent = 'Ingesting…';
    try {
      const res = await triggerPersonalIngest(false);
      const added = (res.results || []).filter(r => r.wiki_path && !r.error).length;
      showToast(`Ingested ${added} file(s). Wiki now has ${res.status?.wiki ?? '?'} entries.`);
      refreshPersonalSummary();
    } catch (err) {
      showToast('Ingest failed: ' + err.message);
    } finally {
      btn.disabled = false;
      btn.textContent = 'Ingest inbox';
    }
  });
  for (const f of SETTINGS_FIELDS) {
    const wrap = document.createElement('label');
    wrap.className = 'flex flex-col gap-1.5';
    const labelText = `<span class="text-[12px] font-medium text-gray-600 dark:text-gray-400">${f.label}</span>`;
    const val = current[f.key];
    let inputHtml;
    if (f.type === 'checkbox') {
      wrap.className = 'flex items-center justify-between py-1';
      inputHtml = `<input type="checkbox" name="${f.key}" ${val ? 'checked' : ''} class="w-5 h-5 accent-sysblue">`;
      wrap.innerHTML = `<span class="text-[13px] text-gray-700 dark:text-gray-300">${f.label}</span>${inputHtml}`;
    } else if (f.type === 'csv-list') {
      // Edit a List[str] as a single comma-separated input. Server-side
      // schemas expect arrays; the form-submit step parses back.
      const placeholder = f.placeholder || '';
      inputHtml = `<input type="text" name="${f.key}" value="${escapeHtml(csvFormat(val))}" placeholder="${placeholder}"
        class="px-3 py-2 text-[13px] border border-gray-300 dark:border-white/[0.12] bg-white dark:bg-[#2c2c2e] focus:outline-none focus:border-sysblue focus:ring-2 focus:ring-sysblue/20 transition-all">`;
      wrap.innerHTML = labelText + inputHtml;
    } else {
      const extra = f.step ? `step="${f.step}"` : '';
      const range = f.min !== undefined ? `min="${f.min}" max="${f.max}"` : '';
      inputHtml = `<input type="${f.type}" name="${f.key}" value="${escapeHtml(String(val ?? ''))}" placeholder="${f.placeholder || ''}" ${extra} ${range}
        class="px-3 py-2 text-[13px] border border-gray-300 dark:border-white/[0.12] bg-white dark:bg-[#2c2c2e] focus:outline-none focus:border-sysblue focus:ring-2 focus:ring-sysblue/20 transition-all">`;
      wrap.innerHTML = labelText + inputHtml;
    }
    form.appendChild(wrap);
  }
  $('settingsSheet').classList.remove('hidden');
}

function closeSettings() {
  $('settingsSheet').classList.add('hidden');
}

async function saveSettings(ev) {
  ev.preventDefault();
  const fd = new FormData(ev.target);
  // Start from the current settings on the server so we don't blank any unmodelled fields.
  let current = {};
  try { current = await apiGet('/api/settings'); } catch {}
  const next = {...current};
  for (const f of SETTINGS_FIELDS) {
    if (f.type === 'checkbox') {
      next[f.key] = fd.get(f.key) !== null;
    } else if (f.type === 'number') {
      const raw = fd.get(f.key);
      next[f.key] = raw === '' || raw === null ? 0 : Number(raw);
    } else if (f.type === 'csv-list') {
      next[f.key] = csvParse(fd.get(f.key));
    } else {
      next[f.key] = fd.get(f.key) ?? '';
    }
  }
  try {
    await apiPost('/api/settings', next);
    state.allowVlms = !!next.enable_vlms;
    showToast('Saved');
    closeSettings();
  } catch (err) {
    showToast('Save failed: ' + err.message);
  }
}

// ─── Init ────────────────────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', () => {
  $('composer').addEventListener('submit', (e) => { e.preventDefault(); send(); });
  $('attachBtn').addEventListener('click', () => $('fileInput').click());
  $('fileInput').addEventListener('change', (e) => { onFilesPicked(e.target.files); e.target.value = ''; });
  $('newChatBtn').addEventListener('click', newChat);
  $('settingsBtn').addEventListener('click', openSettings);
  $('closeSettingsBtn').addEventListener('click', closeSettings);
  $('cancelSettingsBtn').addEventListener('click', closeSettings);
  $('settingsOverlay').addEventListener('click', closeSettings);
  $('settingsForm').addEventListener('submit', saveSettings);

  $('prompt').addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); send(); }
  });
  document.addEventListener('keydown', (e) => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'n') { e.preventDefault(); newChat(); }
    if (e.key === 'Escape') closeSettings();
  });

  refreshConversations();
  refreshPreferences();
  $('prompt').focus();
});
